name: .NET Package

on:
  push:
    tags:
      - "*"
  release:
    types:
      - published
env:
  PROJECT_DIR: '.'
  PROJECT_NAME: Umbraco.StorageProviders.AWSS3

  GITHUB_FEED: https://nuget.pkg.github.com/OvalUK/
  GITHUB_USER: ${{ github.actor }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    # if: github.event_name == 'release'
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet package -c Release
    - name: Pack
      run: |
        arrTag=(${GITHUB_REF//\// })
        VERSION="${arrTag[2]}"
        VERSION="${VERSION//v}"
        dotnet pack -c Release --no-restore --include-symbols --include-source -p:PackageVersion=$VERSION $PROJECT_DIR/$PROJECT_NAME.csproj
    - name: Add GRP Source
      run: dotnet nuget add source https://nuget.pkg.github.com/ovaluk/index.json -n "GRP" -u $GITHUB_USER -p $GITHUB_TOKEN --store-password-in-clear-text
    - name: Publish package to repo
      run: |
        for f in "./bin/Release/*$VERSION.nupkg"
        do
          dotnet nuget push $f --source "GRP" --skip-duplicate --api-key $GITHUB_TOKEN
        done
